version: '3.8'

services:
  rabbitmq-publisher:
    build:
      context: ..
      dockerfile: ./rabbitmq-publisher/Dockerfile.publisher
    volumes:
      - ../:/app
    working_dir: /app/rabbitmq-publisher
    command: ["node", "cron-publisher.js"]
